# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sheldon Chean
email: shelchean@gmail.com
description: >+
 Nothing can happen until you swing the bat.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://toashel.github.io" # the base hostname & protocol for your site
twitter_username: toashel
github_username:  toashel
gems:
 - jekyll-seo-tag
twitter:
 username: toashel
# Build settings
markdown: kramdown