# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: toashel
email: shelchean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hi, I'm Shel! Born and raised in Auckland, New Zealand, I'm currently in my 
third year of a Bachelor of Science in Computer Science from the 
University of Auckland.

I am interested in creating accessible software for end users, and working in
programming translations. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: toashel
github_username:  toashel

# Build settings
markdown: kramdown
