# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: toashel
email: shelchean@gmail.com
description: >+
 My blog about development, books, video games and Japanese media.

baseurl: "/site" # the subpath of your site, e.g. /blog
url: "http://toashel.github.io" # the base hostname & protocol for your site
twitter_username: toashel
github_username:  toashel

# Build settings
markdown: kramdown
